{
 "title": "OpenCost / Cloud Costs (Prometheus Exporter)",
 "tags": [
  "opencost",
  "cloudcost",
  "prometheus"
 ],
 "time": { "from": "now-$window", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   { "name": "window", "label": "Window", "query": "7d,14d,30d,60d,90d" },
   {
    "name": "costMetric",
    "label": "Cost metric",
    "query": "amortizedNetCost,netCost,amortizedCost,listCost"
   },
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(opencost_cloudcost_service_cost{window=\"$window\",cost_metric=\"$costMetric\"}, service)"
    }
   },
   {
    "name": "resource",
    "label": "Resource",
    "query": {
     "query": "label_values(opencost_cloudcost_aggregate_cost{aggregate=\"item\",window=\"$window\",cost_metric=\"$costMetric\",name=~\".*/${service:regex}$\"}, name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cumulative cost for $window (by day)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "max without(day,instance,job,namespace,pod,container,endpoint,deployment,machine,pod_template_hash,ready,app_kubernetes_io_instance,app_kubernetes_io_managed_by,app_kubernetes_io_name,app_kubernetes_io_version,helm_sh_chart) (opencost_cloudcost_daily_total_cost{window=\"$window\",cost_metric=\"$costMetric\"})",
     "legendFormat": "Cost"
    }
   ]
  },
  {
   "title": "Daily cost ($service)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "max without(day,instance,job,namespace,pod,container,endpoint,deployment,machine,pod_template_hash,ready,app_kubernetes_io_instance,app_kubernetes_io_managed_by,app_kubernetes_io_name,app_kubernetes_io_version,helm_sh_chart) (opencost_cloudcost_daily_service_cost{service=\"$service\",window=\"$window\",cost_metric=\"$costMetric\"})",
     "legendFormat": "Cost"
    }
   ]
  },
  {
   "title": "Tables",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cloud costs by service ($window)",
     "type": "table",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "expr": "opencost_cloudcost_service_cost{window=\"$window\",cost_metric=\"$costMetric\"}"
      }
     ]
    },
    {
     "title": "Resources for $service ($window)",
     "type": "table",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "expr": "topk(500, opencost_cloudcost_aggregate_cost{aggregate=\"item\",window=\"$window\",cost_metric=\"$costMetric\",name=~\".*/${service:regex}$\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Resource details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Daily cost ($resource)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "expr": "max without(day,instance,job,namespace,pod,container,endpoint,deployment,machine,pod_template_hash,ready,app_kubernetes_io_instance,app_kubernetes_io_managed_by,app_kubernetes_io_name,app_kubernetes_io_version,helm_sh_chart) (opencost_cloudcost_daily_aggregate_cost{aggregate=\"item\",name=\"$resource\",window=\"$window\",cost_metric=\"$costMetric\"})",
       "legendFormat": "Cost"
      }
     ]
    },
    {
     "title": "Daily costs table ($resource)",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "expr": "last_over_time(opencost_cloudcost_daily_aggregate_cost{aggregate=\"item\",name=\"$resource\",window=\"$window\",cost_metric=\"$costMetric\"}[$window])"
      }
     ]
    }
   ]
  },
  {
   "title": "Daily cost by resources (top 10)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "max without(day,instance,job,namespace,pod,container,endpoint,deployment,machine,pod_template_hash,ready,app_kubernetes_io_instance,app_kubernetes_io_managed_by,app_kubernetes_io_name,app_kubernetes_io_version,helm_sh_chart) (last_over_time(opencost_cloudcost_daily_service_cost{window=\"$window\",cost_metric=\"$costMetric\"}[25h]) and on(service) topk(10, last_over_time(opencost_cloudcost_service_cost{window=\"$window\",cost_metric=\"$costMetric\"}[13h])))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Daily cost by resource items (top 10)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "max without(day,instance,job,namespace,pod,container,endpoint,deployment,machine,pod_template_hash,ready,app_kubernetes_io_instance,app_kubernetes_io_managed_by,app_kubernetes_io_name,app_kubernetes_io_version,helm_sh_chart) (last_over_time(opencost_cloudcost_daily_aggregate_cost{aggregate=\"item\",window=\"$window\",cost_metric=\"$costMetric\"}[25h]) and on(name) topk(10, last_over_time(opencost_cloudcost_aggregate_cost{aggregate=\"item\",window=\"$window\",cost_metric=\"$costMetric\"}[13h])))",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}